<?php

class KabKotaTableSeeder extends Seeder
{

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $kabkota = [
            ['kode_prov' => '11', 'prov' => 'aceh', 'kode_kab' => '1101', 'status' => 'Kabupaten' ,'kab' => 'Simeulue', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '11', 'prov' => 'aceh', 'kode_kab' => '1102', 'status' => 'Kabupaten' ,'kab' => 'Aceh Singkil', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '11', 'prov' => 'aceh', 'kode_kab' => '1103', 'status' => 'Kabupaten' ,'kab' => 'Aceh Selatan', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '11', 'prov' => 'aceh', 'kode_kab' => '1104', 'status' => 'Kabupaten' ,'kab' => 'Aceh Tenggara', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '11', 'prov' => 'aceh', 'kode_kab' => '1105', 'status' => 'Kabupaten' ,'kab' => 'Aceh Timur', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '11', 'prov' => 'aceh', 'kode_kab' => '1106', 'status' => 'Kabupaten' ,'kab' => 'Aceh Tengah', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '11', 'prov' => 'aceh', 'kode_kab' => '1107', 'status' => 'Kabupaten' ,'kab' => 'Aceh Barat', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '11', 'prov' => 'aceh', 'kode_kab' => '1108', 'status' => 'Kabupaten' ,'kab' => 'Aceh Besar', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '11', 'prov' => 'aceh', 'kode_kab' => '1109', 'status' => 'Kabupaten' ,'kab' => 'Pidie', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '11', 'prov' => 'aceh', 'kode_kab' => '1110', 'status' => 'Kabupaten' ,'kab' => 'Bireuen', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '11', 'prov' => 'aceh', 'kode_kab' => '1111', 'status' => 'Kabupaten' ,'kab' => 'Aceh Utara', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '11', 'prov' => 'aceh', 'kode_kab' => '1112', 'status' => 'Kabupaten' ,'kab' => 'Aceh Barat Daya', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '11', 'prov' => 'aceh', 'kode_kab' => '1113', 'status' => 'Kabupaten' ,'kab' => 'Gayo Lues', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '11', 'prov' => 'aceh', 'kode_kab' => '1114', 'status' => 'Kabupaten' ,'kab' => 'Aceh Tamiang', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '11', 'prov' => 'aceh', 'kode_kab' => '1115', 'status' => 'Kabupaten' ,'kab' => 'Nagan Raya', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '11', 'prov' => 'aceh', 'kode_kab' => '1116', 'status' => 'Kabupaten' ,'kab' => 'Aceh Jaya', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '11', 'prov' => 'aceh', 'kode_kab' => '1117', 'status' => 'Kabupaten' ,'kab' => 'Bener Meriah', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '11', 'prov' => 'aceh', 'kode_kab' => '1118', 'status' => 'Kabupaten' ,'kab' => 'Pidie Jaya', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '11', 'prov' => 'aceh', 'kode_kab' => '1171', 'status' => 'Kota' ,'kab' => 'Banda Aceh', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '11', 'prov' => 'aceh', 'kode_kab' => '1172', 'status' => 'Kota' ,'kab' => 'Sabang', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '11', 'prov' => 'aceh', 'kode_kab' => '1173', 'status' => 'Kota' ,'kab' => 'Langsa', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '11', 'prov' => 'aceh', 'kode_kab' => '1174', 'status' => 'Kota' ,'kab' => 'Lhokseumawe', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '11', 'prov' => 'aceh', 'kode_kab' => '1175', 'status' => 'Kota' ,'kab' => 'Subulussalam', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '12', 'prov' => 'sumaterautara', 'kode_kab' => '1201', 'status' => 'Kabupaten' ,'kab' => 'Nias', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '12', 'prov' => 'sumaterautara', 'kode_kab' => '1202', 'status' => 'Kabupaten' ,'kab' => 'Mandailing Natal', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '12', 'prov' => 'sumaterautara', 'kode_kab' => '1203', 'status' => 'Kabupaten' ,'kab' => 'Tapanuli Selatan', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '12', 'prov' => 'sumaterautara', 'kode_kab' => '1204', 'status' => 'Kabupaten' ,'kab' => 'Tapanuli Tengah', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '12', 'prov' => 'sumaterautara', 'kode_kab' => '1205', 'status' => 'Kabupaten' ,'kab' => 'Tapanuli Utara', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '12', 'prov' => 'sumaterautara', 'kode_kab' => '1206', 'status' => 'Kabupaten' ,'kab' => 'Toba Samosir', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '12', 'prov' => 'sumaterautara', 'kode_kab' => '1207', 'status' => 'Kabupaten' ,'kab' => 'Labuhan Batu', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '12', 'prov' => 'sumaterautara', 'kode_kab' => '1208', 'status' => 'Kabupaten' ,'kab' => 'Asahan', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '12', 'prov' => 'sumaterautara', 'kode_kab' => '1209', 'status' => 'Kabupaten' ,'kab' => 'Simalungun', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '12', 'prov' => 'sumaterautara', 'kode_kab' => '1210', 'status' => 'Kabupaten' ,'kab' => 'Dairi', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '12', 'prov' => 'sumaterautara', 'kode_kab' => '1211', 'status' => 'Kabupaten' ,'kab' => 'Karo', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '12', 'prov' => 'sumaterautara', 'kode_kab' => '1212', 'status' => 'Kabupaten' ,'kab' => 'Deli Serdang', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '12', 'prov' => 'sumaterautara', 'kode_kab' => '1213', 'status' => 'Kabupaten' ,'kab' => 'Langkat', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '12', 'prov' => 'sumaterautara', 'kode_kab' => '1214', 'status' => 'Kabupaten' ,'kab' => 'Nias Selatan', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '12', 'prov' => 'sumaterautara', 'kode_kab' => '1215', 'status' => 'Kabupaten' ,'kab' => 'Humbang Hasundutan', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '12', 'prov' => 'sumaterautara', 'kode_kab' => '1216', 'status' => 'Kabupaten' ,'kab' => 'Pakpak Barat', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '12', 'prov' => 'sumaterautara', 'kode_kab' => '1217', 'status' => 'Kabupaten' ,'kab' => 'Samosir', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '12', 'prov' => 'sumaterautara', 'kode_kab' => '1218', 'status' => 'Kabupaten' ,'kab' => 'Serdang Bedagai', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '12', 'prov' => 'sumaterautara', 'kode_kab' => '1219', 'status' => 'Kabupaten' ,'kab' => 'Batu Bara', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '12', 'prov' => 'sumaterautara', 'kode_kab' => '1220', 'status' => 'Kabupaten' ,'kab' => 'Padang Lawas Utara', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '12', 'prov' => 'sumaterautara', 'kode_kab' => '1221', 'status' => 'Kabupaten' ,'kab' => 'Padang Lawas', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '12', 'prov' => 'sumaterautara', 'kode_kab' => '1222', 'status' => 'Kabupaten' ,'kab' => 'Labuhan Batu Selatan', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '12', 'prov' => 'sumaterautara', 'kode_kab' => '1223', 'status' => 'Kabupaten' ,'kab' => 'Labuhan Batu Utara', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '12', 'prov' => 'sumaterautara', 'kode_kab' => '1224', 'status' => 'Kabupaten' ,'kab' => 'Nias Utara', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '12', 'prov' => 'sumaterautara', 'kode_kab' => '1225', 'status' => 'Kabupaten' ,'kab' => 'Nias Barat', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '12', 'prov' => 'sumaterautara', 'kode_kab' => '1271', 'status' => 'Kota ' ,'kab' => 'Sibolga', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '12', 'prov' => 'sumaterautara', 'kode_kab' => '1272', 'status' => 'Kota ' ,'kab' => 'Tanjung Balai', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '12', 'prov' => 'sumaterautara', 'kode_kab' => '1273', 'status' => 'Kota ' ,'kab' => 'Pematang Siantar', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '12', 'prov' => 'sumaterautara', 'kode_kab' => '1274', 'status' => 'Kota ' ,'kab' => 'Tebing Tinggi', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '12', 'prov' => 'sumaterautara', 'kode_kab' => '1275', 'status' => 'Kota ' ,'kab' => 'Medan', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '12', 'prov' => 'sumaterautara', 'kode_kab' => '1276', 'status' => 'Kota ' ,'kab' => 'Binjai', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '12', 'prov' => 'sumaterautara', 'kode_kab' => '1277', 'status' => 'Kota ' ,'kab' => 'Padangsidimpuan', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '12', 'prov' => 'sumaterautara', 'kode_kab' => '1278', 'status' => 'Kota ' ,'kab' => 'Gunungsitoli', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '13', 'prov' => 'sumaterabarat', 'kode_kab' => '1301', 'status' => 'Kabupaten' ,'kab' => 'Kepulauan Mentawai', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '13', 'prov' => 'sumaterabarat', 'kode_kab' => '1302', 'status' => 'Kabupaten' ,'kab' => 'Pesisir Selatan', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '13', 'prov' => 'sumaterabarat', 'kode_kab' => '1303', 'status' => 'Kabupaten' ,'kab' => 'Solok', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '13', 'prov' => 'sumaterabarat', 'kode_kab' => '1304', 'status' => 'Kabupaten' ,'kab' => 'Sijunjung', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '13', 'prov' => 'sumaterabarat', 'kode_kab' => '1305', 'status' => 'Kabupaten' ,'kab' => 'Tanah Datar', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '13', 'prov' => 'sumaterabarat', 'kode_kab' => '1306', 'status' => 'Kabupaten' ,'kab' => 'Padang Pariaman', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '13', 'prov' => 'sumaterabarat', 'kode_kab' => '1307', 'status' => 'Kabupaten' ,'kab' => 'Agam', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '13', 'prov' => 'sumaterabarat', 'kode_kab' => '1308', 'status' => 'Kabupaten' ,'kab' => 'Lima Puluh Kota', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '13', 'prov' => 'sumaterabarat', 'kode_kab' => '1309', 'status' => 'Kabupaten' ,'kab' => 'Pasaman', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '13', 'prov' => 'sumaterabarat', 'kode_kab' => '1310', 'status' => 'Kabupaten' ,'kab' => 'Solok Selatan', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '13', 'prov' => 'sumaterabarat', 'kode_kab' => '1311', 'status' => 'Kabupaten' ,'kab' => 'Dharmasraya', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '13', 'prov' => 'sumaterabarat', 'kode_kab' => '1312', 'status' => 'Kabupaten' ,'kab' => 'Pasaman Barat', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '13', 'prov' => 'sumaterabarat', 'kode_kab' => '1371', 'status' => 'Kota ' ,'kab' => 'Padang', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '13', 'prov' => 'sumaterabarat', 'kode_kab' => '1372', 'status' => 'Kota ' ,'kab' => 'Solok', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '13', 'prov' => 'sumaterabarat', 'kode_kab' => '1373', 'status' => 'Kota ' ,'kab' => 'Sawah Lunto', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '13', 'prov' => 'sumaterabarat', 'kode_kab' => '1374', 'status' => 'Kota ' ,'kab' => 'Padang Panjang', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '13', 'prov' => 'sumaterabarat', 'kode_kab' => '1375', 'status' => 'Kota ' ,'kab' => 'Bukittinggi', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '13', 'prov' => 'sumaterabarat', 'kode_kab' => '1376', 'status' => 'Kota ' ,'kab' => 'Payakumbuh', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '13', 'prov' => 'sumaterabarat', 'kode_kab' => '1377', 'status' => 'Kota ' ,'kab' => 'Pariaman', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '14', 'prov' => 'riau', 'kode_kab' => '1401', 'status' => 'Kabupaten' ,'kab' => 'Kuantan Singingi', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '14', 'prov' => 'riau', 'kode_kab' => '1402', 'status' => 'Kabupaten' ,'kab' => 'Indragiri Hulu', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '14', 'prov' => 'riau', 'kode_kab' => '1403', 'status' => 'Kabupaten' ,'kab' => 'Indragiri Hilir', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '14', 'prov' => 'riau', 'kode_kab' => '1404', 'status' => 'Kabupaten' ,'kab' => 'Pelalawan', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '14', 'prov' => 'riau', 'kode_kab' => '1405', 'status' => 'Kabupaten' ,'kab' => 'Sia', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '14', 'prov' => 'riau', 'kode_kab' => '1406', 'status' => 'Kabupaten' ,'kab' => 'Kampar', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '14', 'prov' => 'riau', 'kode_kab' => '1407', 'status' => 'Kabupaten' ,'kab' => 'Rokan Hulu', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '14', 'prov' => 'riau', 'kode_kab' => '1408', 'status' => 'Kabupaten' ,'kab' => 'Bengkalis', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '14', 'prov' => 'riau', 'kode_kab' => '1409', 'status' => 'Kabupaten' ,'kab' => 'Rokan Hilir', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '14', 'prov' => 'riau', 'kode_kab' => '1410', 'status' => 'Kabupaten' ,'kab' => 'Kepulauan Meranti', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '14', 'prov' => 'riau', 'kode_kab' => '1471', 'status' => 'Kota' ,'kab' => 'Pekanbaru', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '14', 'prov' => 'riau', 'kode_kab' => '1473', 'status' => 'Kota' ,'kab' => 'D U M A I', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '15', 'prov' => 'jambi', 'kode_kab' => '1501', 'status' => 'Kabupaten' ,'kab' => 'Kerinci', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '15', 'prov' => 'jambi', 'kode_kab' => '1502', 'status' => 'Kabupaten' ,'kab' => 'Merangin', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '15', 'prov' => 'jambi', 'kode_kab' => '1503', 'status' => 'Kabupaten' ,'kab' => 'Sarolangun', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '15', 'prov' => 'jambi', 'kode_kab' => '1504', 'status' => 'Kabupaten' ,'kab' => 'Batang Hari', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '15', 'prov' => 'jambi', 'kode_kab' => '1505', 'status' => 'Kabupaten' ,'kab' => 'Muaro Jambi', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '15', 'prov' => 'jambi', 'kode_kab' => '1506', 'status' => 'Kabupaten' ,'kab' => 'Tanjung Jabung Timur', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '15', 'prov' => 'jambi', 'kode_kab' => '1507', 'status' => 'Kabupaten' ,'kab' => 'Tanjung Jabung Barat', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '15', 'prov' => 'jambi', 'kode_kab' => '1508', 'status' => 'Kabupaten' ,'kab' => 'Tebo', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '15', 'prov' => 'jambi', 'kode_kab' => '1509', 'status' => 'Kabupaten' ,'kab' => 'Bungo', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '15', 'prov' => 'jambi', 'kode_kab' => '1571', 'status' => 'Kota' ,'kab' => 'Jambi', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '15', 'prov' => 'jambi', 'kode_kab' => '1572', 'status' => 'Kota' ,'kab' => 'Sungai Penuh', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '16', 'prov' => 'sumateraselatan', 'kode_kab' => '1601', 'status' => 'Kabupaten' ,'kab' => 'Ogan Komering Ulu', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '16', 'prov' => 'sumateraselatan', 'kode_kab' => '1602', 'status' => 'Kabupaten' ,'kab' => 'Ogan Komering Ilir', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '16', 'prov' => 'sumateraselatan', 'kode_kab' => '1603', 'status' => 'Kabupaten' ,'kab' => 'Muara Enim', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '16', 'prov' => 'sumateraselatan', 'kode_kab' => '1604', 'status' => 'Kabupaten' ,'kab' => 'Lahat', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '16', 'prov' => 'sumateraselatan', 'kode_kab' => '1605', 'status' => 'Kabupaten' ,'kab' => 'Musi Rawas', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '16', 'prov' => 'sumateraselatan', 'kode_kab' => '1606', 'status' => 'Kabupaten' ,'kab' => 'Musi Banyuasin', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '16', 'prov' => 'sumateraselatan', 'kode_kab' => '1607', 'status' => 'Kabupaten' ,'kab' => 'Banyu Asin', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '16', 'prov' => 'sumateraselatan', 'kode_kab' => '1608', 'status' => 'Kabupaten' ,'kab' => 'Ogan Komering Ulu Selatan', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '16', 'prov' => 'sumateraselatan', 'kode_kab' => '1609', 'status' => 'Kabupaten' ,'kab' => 'Ogan Komering Ulu Timur', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '16', 'prov' => 'sumateraselatan', 'kode_kab' => '1610', 'status' => 'Kabupaten' ,'kab' => 'Ogan Ilir', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '16', 'prov' => 'sumateraselatan', 'kode_kab' => '1611', 'status' => 'Kabupaten' ,'kab' => 'Empat Lawang', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '16', 'prov' => 'sumateraselatan', 'kode_kab' => '1671', 'status' => 'Kota' ,'kab' => 'Palembang', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '16', 'prov' => 'sumateraselatan', 'kode_kab' => '1672', 'status' => 'Kota' ,'kab' => 'Prabumulih', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '16', 'prov' => 'sumateraselatan', 'kode_kab' => '1673', 'status' => 'Kota' ,'kab' => 'Pagar Alam', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '16', 'prov' => 'sumateraselatan', 'kode_kab' => '1674', 'status' => 'Kota' ,'kab' => 'Lubuklinggau', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '17', 'prov' => 'bengkulu', 'kode_kab' => '1701', 'status' => 'Kabupaten' ,'kab' => 'Bengkulu Selatan', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '17', 'prov' => 'bengkulu', 'kode_kab' => '1702', 'status' => 'Kabupaten' ,'kab' => 'Rejang Lebong', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '17', 'prov' => 'bengkulu', 'kode_kab' => '1703', 'status' => 'Kabupaten' ,'kab' => 'Bengkulu Utara', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '17', 'prov' => 'bengkulu', 'kode_kab' => '1704', 'status' => 'Kabupaten' ,'kab' => 'Kaur', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '17', 'prov' => 'bengkulu', 'kode_kab' => '1705', 'status' => 'Kabupaten' ,'kab' => 'Seluma', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '17', 'prov' => 'bengkulu', 'kode_kab' => '1706', 'status' => 'Kabupaten' ,'kab' => 'Mukomuko', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '17', 'prov' => 'bengkulu', 'kode_kab' => '1707', 'status' => 'Kabupaten' ,'kab' => 'Lebong', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '17', 'prov' => 'bengkulu', 'kode_kab' => '1708', 'status' => 'Kabupaten' ,'kab' => 'Kepahiang', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '17', 'prov' => 'bengkulu', 'kode_kab' => '1709', 'status' => 'Kabupaten' ,'kab' => 'Bengkulu Tengah', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '17', 'prov' => 'bengkulu', 'kode_kab' => '1771', 'status' => 'Kota' ,'kab' => 'Bengkulu', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '18', 'prov' => 'lampung', 'kode_kab' => '1801', 'status' => 'Kabupaten' ,'kab' => 'Lampung Barat', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '18', 'prov' => 'lampung', 'kode_kab' => '1802', 'status' => 'Kabupaten' ,'kab' => 'Tanggamus', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '18', 'prov' => 'lampung', 'kode_kab' => '1803', 'status' => 'Kabupaten' ,'kab' => 'Lampung Selatan', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '18', 'prov' => 'lampung', 'kode_kab' => '1804', 'status' => 'Kabupaten' ,'kab' => 'Lampung Timur', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '18', 'prov' => 'lampung', 'kode_kab' => '1805', 'status' => 'Kabupaten' ,'kab' => 'Lampung Tengah', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '18', 'prov' => 'lampung', 'kode_kab' => '1806', 'status' => 'Kabupaten' ,'kab' => 'Lampung Utara', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '18', 'prov' => 'lampung', 'kode_kab' => '1807', 'status' => 'Kabupaten' ,'kab' => 'Way Kanan', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '18', 'prov' => 'lampung', 'kode_kab' => '1808', 'status' => 'Kabupaten' ,'kab' => 'Tulangbawang', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '18', 'prov' => 'lampung', 'kode_kab' => '1809', 'status' => 'Kabupaten' ,'kab' => 'Pesawaran', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '18', 'prov' => 'lampung', 'kode_kab' => '1810', 'status' => 'Kabupaten' ,'kab' => 'Pringsewu', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '18', 'prov' => 'lampung', 'kode_kab' => '1811', 'status' => 'Kabupaten' ,'kab' => 'Mesuji', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '18', 'prov' => 'lampung', 'kode_kab' => '1812', 'status' => 'Kabupaten' ,'kab' => 'Tulang Bawang Barat', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '18', 'prov' => 'lampung', 'kode_kab' => '1871', 'status' => 'Kota' ,'kab' => 'Bandar Lampung', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '18', 'prov' => 'lampung', 'kode_kab' => '1872', 'status' => 'Kota' ,'kab' => 'Metro', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '19', 'prov' => 'kepbangkabelitung', 'kode_kab' => '1901', 'status' => 'Kabupaten' ,'kab' => 'Bangka', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '19', 'prov' => 'kepbangkabelitung', 'kode_kab' => '1902', 'status' => 'Kabupaten' ,'kab' => 'Belitung', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '19', 'prov' => 'kepbangkabelitung', 'kode_kab' => '1903', 'status' => 'Kabupaten' ,'kab' => 'Bangka Barat', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '19', 'prov' => 'kepbangkabelitung', 'kode_kab' => '1904', 'status' => 'Kabupaten' ,'kab' => 'Bangka Tengah', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '19', 'prov' => 'kepbangkabelitung', 'kode_kab' => '1905', 'status' => 'Kabupaten' ,'kab' => 'Bangka Selatan', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '19', 'prov' => 'kepbangkabelitung', 'kode_kab' => '1906', 'status' => 'Kabupaten' ,'kab' => 'Belitung Timur', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '19', 'prov' => 'kepbangkabelitung', 'kode_kab' => '1971', 'status' => 'Kabupaten' ,'kab' => 'Pangkal Pinang', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '21', 'prov' => 'kepriau', 'kode_kab' => '2101', 'status' => 'Kabupaten' ,'kab' => 'Karimun', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '21', 'prov' => 'kepriau', 'kode_kab' => '2102', 'status' => 'Kabupaten' ,'kab' => 'Bintan', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '21', 'prov' => 'kepriau', 'kode_kab' => '2103', 'status' => 'Kabupaten' ,'kab' => 'Natuna', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '21', 'prov' => 'kepriau', 'kode_kab' => '2104', 'status' => 'Kabupaten' ,'kab' => 'Lingga', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '21', 'prov' => 'kepriau', 'kode_kab' => '2105', 'status' => 'Kabupaten' ,'kab' => 'Kepulauan Anambas', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '21', 'prov' => 'kepriau', 'kode_kab' => '2171', 'status' => 'Kota' ,'kab' => 'Bata', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '21', 'prov' => 'kepriau', 'kode_kab' => '2172', 'status' => 'Kota' ,'kab' => 'Tanjung Pinang', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '31', 'prov' => 'dkijakarta', 'kode_kab' => '3101', 'status' => 'Kabupaten' ,'kab' => 'Kepulauan Seribu', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '31', 'prov' => 'dkijakarta', 'kode_kab' => '3171', 'status' => 'Kota' ,'kab' => 'Jakarta Selatan', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '31', 'prov' => 'dkijakarta', 'kode_kab' => '3172', 'status' => 'Kota' ,'kab' => 'Jakarta Timur', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '31', 'prov' => 'dkijakarta', 'kode_kab' => '3173', 'status' => 'Kota' ,'kab' => 'Jakarta Pusat', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '31', 'prov' => 'dkijakarta', 'kode_kab' => '3174', 'status' => 'Kota' ,'kab' => 'Jakarta Barat', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '31', 'prov' => 'dkijakarta', 'kode_kab' => '3175', 'status' => 'Kota' ,'kab' => 'Jakarta Utara', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '32', 'prov' => 'jawabarat', 'kode_kab' => '3201', 'status' => 'Kabupaten' ,'kab' => 'Bogor', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '32', 'prov' => 'jawabarat', 'kode_kab' => '3202', 'status' => 'Kabupaten' ,'kab' => 'Sukabumi', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '32', 'prov' => 'jawabarat', 'kode_kab' => '3203', 'status' => 'Kabupaten' ,'kab' => 'Cianjur', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '32', 'prov' => 'jawabarat', 'kode_kab' => '3204', 'status' => 'Kabupaten' ,'kab' => 'Bandung', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '32', 'prov' => 'jawabarat', 'kode_kab' => '3205', 'status' => 'Kabupaten' ,'kab' => 'Garut', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '32', 'prov' => 'jawabarat', 'kode_kab' => '3206', 'status' => 'Kabupaten' ,'kab' => 'Tasikmalaya', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '32', 'prov' => 'jawabarat', 'kode_kab' => '3207', 'status' => 'Kabupaten' ,'kab' => 'Ciamis', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '32', 'prov' => 'jawabarat', 'kode_kab' => '3208', 'status' => 'Kabupaten' ,'kab' => 'Kuningan', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '32', 'prov' => 'jawabarat', 'kode_kab' => '3209', 'status' => 'Kabupaten' ,'kab' => 'Cirebon', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '32', 'prov' => 'jawabarat', 'kode_kab' => '3210', 'status' => 'Kabupaten' ,'kab' => 'Majalengka', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '32', 'prov' => 'jawabarat', 'kode_kab' => '3211', 'status' => 'Kabupaten' ,'kab' => 'Sumedang', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '32', 'prov' => 'jawabarat', 'kode_kab' => '3212', 'status' => 'Kabupaten' ,'kab' => 'Indramayu', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '32', 'prov' => 'jawabarat', 'kode_kab' => '3213', 'status' => 'Kabupaten' ,'kab' => 'Subang', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '32', 'prov' => 'jawabarat', 'kode_kab' => '3214', 'status' => 'Kabupaten' ,'kab' => 'Purwakarta', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '32', 'prov' => 'jawabarat', 'kode_kab' => '3215', 'status' => 'Kabupaten' ,'kab' => 'Karawang', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '32', 'prov' => 'jawabarat', 'kode_kab' => '3216', 'status' => 'Kabupaten' ,'kab' => 'Bekasi', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '32', 'prov' => 'jawabarat', 'kode_kab' => '3217', 'status' => 'Kabupaten' ,'kab' => 'Bandung Barat', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '32', 'prov' => 'jawabarat', 'kode_kab' => '3271', 'status' => 'Kota' ,'kab' => 'Bogor', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '32', 'prov' => 'jawabarat', 'kode_kab' => '3272', 'status' => 'Kota' ,'kab' => 'Sukabumi', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '32', 'prov' => 'jawabarat', 'kode_kab' => '3273', 'status' => 'Kota' ,'kab' => 'Bandung', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '32', 'prov' => 'jawabarat', 'kode_kab' => '3274', 'status' => 'Kota' ,'kab' => 'Cirebon', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '32', 'prov' => 'jawabarat', 'kode_kab' => '3275', 'status' => 'Kota' ,'kab' => 'Bekasi', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '32', 'prov' => 'jawabarat', 'kode_kab' => '3276', 'status' => 'Kota' ,'kab' => 'Depok', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '32', 'prov' => 'jawabarat', 'kode_kab' => '3277', 'status' => 'Kota' ,'kab' => 'Cimahi', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '32', 'prov' => 'jawabarat', 'kode_kab' => '3278', 'status' => 'Kota' ,'kab' => 'Tasikmalaya', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '32', 'prov' => 'jawabarat', 'kode_kab' => '3279', 'status' => 'Kota' ,'kab' => 'Banjar', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '33', 'prov' => 'jawatengah', 'kode_kab' => '3301', 'status' => 'Kabupaten' ,'kab' => 'Cilacap', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '33', 'prov' => 'jawatengah', 'kode_kab' => '3302', 'status' => 'Kabupaten' ,'kab' => 'Banyumas', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '33', 'prov' => 'jawatengah', 'kode_kab' => '3303', 'status' => 'Kabupaten' ,'kab' => 'Purbalingga', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '33', 'prov' => 'jawatengah', 'kode_kab' => '3304', 'status' => 'Kabupaten' ,'kab' => 'Banjarnegara', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '33', 'prov' => 'jawatengah', 'kode_kab' => '3305', 'status' => 'Kabupaten' ,'kab' => 'Kebumen', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '33', 'prov' => 'jawatengah', 'kode_kab' => '3306', 'status' => 'Kabupaten' ,'kab' => 'Purworejo', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '33', 'prov' => 'jawatengah', 'kode_kab' => '3307', 'status' => 'Kabupaten' ,'kab' => 'Wonosobo', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '33', 'prov' => 'jawatengah', 'kode_kab' => '3308', 'status' => 'Kabupaten' ,'kab' => 'Magelang', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '33', 'prov' => 'jawatengah', 'kode_kab' => '3309', 'status' => 'Kabupaten' ,'kab' => 'Boyolali', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '33', 'prov' => 'jawatengah', 'kode_kab' => '3310', 'status' => 'Kabupaten' ,'kab' => 'Klaten', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '33', 'prov' => 'jawatengah', 'kode_kab' => '3311', 'status' => 'Kabupaten' ,'kab' => 'Sukoharjo', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '33', 'prov' => 'jawatengah', 'kode_kab' => '3312', 'status' => 'Kabupaten' ,'kab' => 'Wonogiri', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '33', 'prov' => 'jawatengah', 'kode_kab' => '3313', 'status' => 'Kabupaten' ,'kab' => 'Karanganyar', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '33', 'prov' => 'jawatengah', 'kode_kab' => '3314', 'status' => 'Kabupaten' ,'kab' => 'Sragen', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '33', 'prov' => 'jawatengah', 'kode_kab' => '3315', 'status' => 'Kabupaten' ,'kab' => 'Grobogan', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '33', 'prov' => 'jawatengah', 'kode_kab' => '3316', 'status' => 'Kabupaten' ,'kab' => 'Blora', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '33', 'prov' => 'jawatengah', 'kode_kab' => '3317', 'status' => 'Kabupaten' ,'kab' => 'Rembang', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '33', 'prov' => 'jawatengah', 'kode_kab' => '3318', 'status' => 'Kabupaten' ,'kab' => 'Pati', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '33', 'prov' => 'jawatengah', 'kode_kab' => '3319', 'status' => 'Kabupaten' ,'kab' => 'Kudus', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '33', 'prov' => 'jawatengah', 'kode_kab' => '3320', 'status' => 'Kabupaten' ,'kab' => 'Jepara', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '33', 'prov' => 'jawatengah', 'kode_kab' => '3321', 'status' => 'Kabupaten' ,'kab' => 'Demak', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '33', 'prov' => 'jawatengah', 'kode_kab' => '3322', 'status' => 'Kabupaten' ,'kab' => 'Semarang', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '33', 'prov' => 'jawatengah', 'kode_kab' => '3323', 'status' => 'Kabupaten' ,'kab' => 'Temanggung', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '33', 'prov' => 'jawatengah', 'kode_kab' => '3324', 'status' => 'Kabupaten' ,'kab' => 'Kendal', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '33', 'prov' => 'jawatengah', 'kode_kab' => '3325', 'status' => 'Kabupaten' ,'kab' => 'Batang', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '33', 'prov' => 'jawatengah', 'kode_kab' => '3326', 'status' => 'Kabupaten' ,'kab' => 'Pekalongan', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '33', 'prov' => 'jawatengah', 'kode_kab' => '3327', 'status' => 'Kabupaten' ,'kab' => 'Pemalang', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '33', 'prov' => 'jawatengah', 'kode_kab' => '3328', 'status' => 'Kabupaten' ,'kab' => 'Tegal', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '33', 'prov' => 'jawatengah', 'kode_kab' => '3329', 'status' => 'Kabupaten' ,'kab' => 'Brebes', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '33', 'prov' => 'jawatengah', 'kode_kab' => '3371', 'status' => 'Kota' ,'kab' => 'Magelang', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '33', 'prov' => 'jawatengah', 'kode_kab' => '3372', 'status' => 'Kota' ,'kab' => 'Surakarta', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '33', 'prov' => 'jawatengah', 'kode_kab' => '3373', 'status' => 'Kota' ,'kab' => 'Salatiga', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '33', 'prov' => 'jawatengah', 'kode_kab' => '3374', 'status' => 'Kota' ,'kab' => 'Semarang', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '33', 'prov' => 'jawatengah', 'kode_kab' => '3375', 'status' => 'Kota' ,'kab' => 'Pekalongan', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '33', 'prov' => 'jawatengah', 'kode_kab' => '3376', 'status' => 'Kota' ,'kab' => 'Tegal', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '34', 'prov' => 'diyogyakarta', 'kode_kab' => '3401', 'status' => 'Kabupaten' ,'kab' => 'Kulon Progo', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '34', 'prov' => 'diyogyakarta', 'kode_kab' => '3402', 'status' => 'Kabupaten' ,'kab' => 'Bantul', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '34', 'prov' => 'diyogyakarta', 'kode_kab' => '3403', 'status' => 'Kabupaten' ,'kab' => 'Gunung Kidul', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '34', 'prov' => 'diyogyakarta', 'kode_kab' => '3404', 'status' => 'Kabupaten' ,'kab' => 'Sleman', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '34', 'prov' => 'diyogyakarta', 'kode_kab' => '3471', 'status' => 'Kota' ,'kab' => 'Yogyakarta', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '35', 'prov' => 'jawatimur', 'kode_kab' => '3501', 'status' => 'Kabupaten' ,'kab' => 'Pacitan', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '35', 'prov' => 'jawatimur', 'kode_kab' => '3502', 'status' => 'Kabupaten' ,'kab' => 'Ponorogo', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '35', 'prov' => 'jawatimur', 'kode_kab' => '3503', 'status' => 'Kabupaten' ,'kab' => 'Trenggalek', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '35', 'prov' => 'jawatimur', 'kode_kab' => '3504', 'status' => 'Kabupaten' ,'kab' => 'Tulungagung', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '35', 'prov' => 'jawatimur', 'kode_kab' => '3505', 'status' => 'Kabupaten' ,'kab' => 'Blitar', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '35', 'prov' => 'jawatimur', 'kode_kab' => '3506', 'status' => 'Kabupaten' ,'kab' => 'Kediri', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '35', 'prov' => 'jawatimur', 'kode_kab' => '3507', 'status' => 'Kabupaten' ,'kab' => 'Malang', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '35', 'prov' => 'jawatimur', 'kode_kab' => '3508', 'status' => 'Kabupaten' ,'kab' => 'Lumajang', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '35', 'prov' => 'jawatimur', 'kode_kab' => '3509', 'status' => 'Kabupaten' ,'kab' => 'Jember', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '35', 'prov' => 'jawatimur', 'kode_kab' => '3510', 'status' => 'Kabupaten' ,'kab' => 'Banyuwangi', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '35', 'prov' => 'jawatimur', 'kode_kab' => '3511', 'status' => 'Kabupaten' ,'kab' => 'Bondowoso', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '35', 'prov' => 'jawatimur', 'kode_kab' => '3512', 'status' => 'Kabupaten' ,'kab' => 'Situbondo', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '35', 'prov' => 'jawatimur', 'kode_kab' => '3513', 'status' => 'Kabupaten' ,'kab' => 'Probolinggo', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '35', 'prov' => 'jawatimur', 'kode_kab' => '3514', 'status' => 'Kabupaten' ,'kab' => 'Pasuruan', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '35', 'prov' => 'jawatimur', 'kode_kab' => '3515', 'status' => 'Kabupaten' ,'kab' => 'Sidoarjo', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '35', 'prov' => 'jawatimur', 'kode_kab' => '3516', 'status' => 'Kabupaten' ,'kab' => 'Mojokerto', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '35', 'prov' => 'jawatimur', 'kode_kab' => '3517', 'status' => 'Kabupaten' ,'kab' => 'Jombang', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '35', 'prov' => 'jawatimur', 'kode_kab' => '3518', 'status' => 'Kabupaten' ,'kab' => 'Nganjuk', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '35', 'prov' => 'jawatimur', 'kode_kab' => '3519', 'status' => 'Kabupaten' ,'kab' => 'Madiun', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '35', 'prov' => 'jawatimur', 'kode_kab' => '3520', 'status' => 'Kabupaten' ,'kab' => 'Magetan', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '35', 'prov' => 'jawatimur', 'kode_kab' => '3521', 'status' => 'Kabupaten' ,'kab' => 'Ngawi', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '35', 'prov' => 'jawatimur', 'kode_kab' => '3522', 'status' => 'Kabupaten' ,'kab' => 'Bojonegoro', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '35', 'prov' => 'jawatimur', 'kode_kab' => '3523', 'status' => 'Kabupaten' ,'kab' => 'Tuban', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '35', 'prov' => 'jawatimur', 'kode_kab' => '3524', 'status' => 'Kabupaten' ,'kab' => 'Lamongan', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '35', 'prov' => 'jawatimur', 'kode_kab' => '3525', 'status' => 'Kabupaten' ,'kab' => 'Gresik', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '35', 'prov' => 'jawatimur', 'kode_kab' => '3526', 'status' => 'Kabupaten' ,'kab' => 'Bangkalan', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '35', 'prov' => 'jawatimur', 'kode_kab' => '3527', 'status' => 'Kabupaten' ,'kab' => 'Sampang', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '35', 'prov' => 'jawatimur', 'kode_kab' => '3528', 'status' => 'Kabupaten' ,'kab' => 'Pamekasan', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '35', 'prov' => 'jawatimur', 'kode_kab' => '3529', 'status' => 'Kabupaten' ,'kab' => 'Sumenep', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '35', 'prov' => 'jawatimur', 'kode_kab' => '3571', 'status' => 'Kota' ,'kab' => 'Kediri', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '35', 'prov' => 'jawatimur', 'kode_kab' => '3572', 'status' => 'Kota' ,'kab' => 'Blitar', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '35', 'prov' => 'jawatimur', 'kode_kab' => '3573', 'status' => 'Kota' ,'kab' => 'Malang', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '35', 'prov' => 'jawatimur', 'kode_kab' => '3574', 'status' => 'Kota' ,'kab' => 'Probolinggo', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '35', 'prov' => 'jawatimur', 'kode_kab' => '3575', 'status' => 'Kota' ,'kab' => 'Pasuruan', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '35', 'prov' => 'jawatimur', 'kode_kab' => '3576', 'status' => 'Kota' ,'kab' => 'Mojokerto', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '35', 'prov' => 'jawatimur', 'kode_kab' => '3577', 'status' => 'Kota' ,'kab' => 'Madiun', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '35', 'prov' => 'jawatimur', 'kode_kab' => '3578', 'status' => 'Kota' ,'kab' => 'Surabaya', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '35', 'prov' => 'jawatimur', 'kode_kab' => '3579', 'status' => 'Kota' ,'kab' => 'Batu', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '36', 'prov' => 'banten', 'kode_kab' => '3601', 'status' => 'Kabupaten' ,'kab' => 'Pandeglang', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '36', 'prov' => 'banten', 'kode_kab' => '3602', 'status' => 'Kabupaten' ,'kab' => 'Lebak', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '36', 'prov' => 'banten', 'kode_kab' => '3603', 'status' => 'Kabupaten' ,'kab' => 'Tangerang', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '36', 'prov' => 'banten', 'kode_kab' => '3604', 'status' => 'Kabupaten' ,'kab' => 'Serang', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '36', 'prov' => 'banten', 'kode_kab' => '3671', 'status' => 'Kota' ,'kab' => 'Tangerang', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '36', 'prov' => 'banten', 'kode_kab' => '3672', 'status' => 'Kota' ,'kab' => 'Cilegon', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '36', 'prov' => 'banten', 'kode_kab' => '3673', 'status' => 'Kota' ,'kab' => 'Serang', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '36', 'prov' => 'banten', 'kode_kab' => '3674', 'status' => 'Kota' ,'kab' => 'Tangerang Selatan', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '51', 'prov' => 'bali', 'kode_kab' => '5101', 'status' => 'Kabupaten' ,'kab' => 'Jembrana', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '51', 'prov' => 'bali', 'kode_kab' => '5102', 'status' => 'Kabupaten' ,'kab' => 'Tabanan', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '51', 'prov' => 'bali', 'kode_kab' => '5103', 'status' => 'Kabupaten' ,'kab' => 'Badung', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '51', 'prov' => 'bali', 'kode_kab' => '5104', 'status' => 'Kabupaten' ,'kab' => 'Gianyar', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '51', 'prov' => 'bali', 'kode_kab' => '5105', 'status' => 'Kabupaten' ,'kab' => 'Klungkung', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '51', 'prov' => 'bali', 'kode_kab' => '5106', 'status' => 'Kabupaten' ,'kab' => 'Bangli', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '51', 'prov' => 'bali', 'kode_kab' => '5107', 'status' => 'Kabupaten' ,'kab' => 'Karang Asem', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '51', 'prov' => 'bali', 'kode_kab' => '5108', 'status' => 'Kabupaten' ,'kab' => 'Buleleng', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '51', 'prov' => 'bali', 'kode_kab' => '5171', 'status' => 'Kota' ,'kab' => 'Denpasar', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '52', 'prov' => 'nusatenggarabarat', 'kode_kab' => '5201', 'status' => 'Kabupaten' ,'kab' => 'Lombok Barat', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '52', 'prov' => 'nusatenggarabarat', 'kode_kab' => '5202', 'status' => 'Kabupaten' ,'kab' => 'Lombok Tengah', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '52', 'prov' => 'nusatenggarabarat', 'kode_kab' => '5203', 'status' => 'Kabupaten' ,'kab' => 'Lombok Timur', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '52', 'prov' => 'nusatenggarabarat', 'kode_kab' => '5204', 'status' => 'Kabupaten' ,'kab' => 'Sumbawa', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '52', 'prov' => 'nusatenggarabarat', 'kode_kab' => '5205', 'status' => 'Kabupaten' ,'kab' => 'Dompu', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '52', 'prov' => 'nusatenggarabarat', 'kode_kab' => '5206', 'status' => 'Kabupaten' ,'kab' => 'Bima', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '52', 'prov' => 'nusatenggarabarat', 'kode_kab' => '5207', 'status' => 'Kabupaten' ,'kab' => 'Sumbawa Barat', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '52', 'prov' => 'nusatenggarabarat', 'kode_kab' => '5208', 'status' => 'Kabupaten' ,'kab' => 'Lombok Utara', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '52', 'prov' => 'nusatenggarabarat', 'kode_kab' => '5271', 'status' => 'Kota' ,'kab' => 'Mataram', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '52', 'prov' => 'nusatenggarabarat', 'kode_kab' => '5272', 'status' => 'Kota' ,'kab' => 'Bima', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '53', 'prov' => 'nusatenggaratimur', 'kode_kab' => '5301', 'status' => 'Kabupaten' ,'kab' => 'Sumba Barat', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '53', 'prov' => 'nusatenggaratimur', 'kode_kab' => '5302', 'status' => 'Kabupaten' ,'kab' => 'Sumba Timur', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '53', 'prov' => 'nusatenggaratimur', 'kode_kab' => '5303', 'status' => 'Kabupaten' ,'kab' => 'Kupang', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '53', 'prov' => 'nusatenggaratimur', 'kode_kab' => '5304', 'status' => 'Kabupaten' ,'kab' => 'Timor Tengah Selatan', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '53', 'prov' => 'nusatenggaratimur', 'kode_kab' => '5305', 'status' => 'Kabupaten' ,'kab' => 'Timor Tengah Utara', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '53', 'prov' => 'nusatenggaratimur', 'kode_kab' => '5306', 'status' => 'Kabupaten' ,'kab' => 'Belu', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '53', 'prov' => 'nusatenggaratimur', 'kode_kab' => '5307', 'status' => 'Kabupaten' ,'kab' => 'Alor', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '53', 'prov' => 'nusatenggaratimur', 'kode_kab' => '5308', 'status' => 'Kabupaten' ,'kab' => 'Lembata', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '53', 'prov' => 'nusatenggaratimur', 'kode_kab' => '5309', 'status' => 'Kabupaten' ,'kab' => 'Flores Timur', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '53', 'prov' => 'nusatenggaratimur', 'kode_kab' => '5310', 'status' => 'Kabupaten' ,'kab' => 'Sikka', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '53', 'prov' => 'nusatenggaratimur', 'kode_kab' => '5311', 'status' => 'Kabupaten' ,'kab' => 'Ende', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '53', 'prov' => 'nusatenggaratimur', 'kode_kab' => '5312', 'status' => 'Kabupaten' ,'kab' => 'Ngada', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '53', 'prov' => 'nusatenggaratimur', 'kode_kab' => '5313', 'status' => 'Kabupaten' ,'kab' => 'Manggarai', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '53', 'prov' => 'nusatenggaratimur', 'kode_kab' => '5314', 'status' => 'Kabupaten' ,'kab' => 'Rote Ndao', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '53', 'prov' => 'nusatenggaratimur', 'kode_kab' => '5315', 'status' => 'Kabupaten' ,'kab' => 'Manggarai Barat', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '53', 'prov' => 'nusatenggaratimur', 'kode_kab' => '5316', 'status' => 'Kabupaten' ,'kab' => 'Sumba Tengah', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '53', 'prov' => 'nusatenggaratimur', 'kode_kab' => '5317', 'status' => 'Kabupaten' ,'kab' => 'Sumba Barat Daya', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '53', 'prov' => 'nusatenggaratimur', 'kode_kab' => '5318', 'status' => 'Kabupaten' ,'kab' => 'Nagekeo', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '53', 'prov' => 'nusatenggaratimur', 'kode_kab' => '5319', 'status' => 'Kabupaten' ,'kab' => 'Manggarai Timur', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '53', 'prov' => 'nusatenggaratimur', 'kode_kab' => '5320', 'status' => 'Kabupaten' ,'kab' => 'Sabu Raijua', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '53', 'prov' => 'nusatenggaratimur', 'kode_kab' => '5371', 'status' => 'Kota' ,'kab' => 'Kupang', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '61', 'prov' => 'kalimantanbarat', 'kode_kab' => '6101', 'status' => 'Kabupaten' ,'kab' => 'Sambas', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '61', 'prov' => 'kalimantanbarat', 'kode_kab' => '6102', 'status' => 'Kabupaten' ,'kab' => 'Bengkayang', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '61', 'prov' => 'kalimantanbarat', 'kode_kab' => '6103', 'status' => 'Kabupaten' ,'kab' => 'Landak', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '61', 'prov' => 'kalimantanbarat', 'kode_kab' => '6104', 'status' => 'Kabupaten' ,'kab' => 'Pontianak', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '61', 'prov' => 'kalimantanbarat', 'kode_kab' => '6105', 'status' => 'Kabupaten' ,'kab' => 'Sanggau', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '61', 'prov' => 'kalimantanbarat', 'kode_kab' => '6106', 'status' => 'Kabupaten' ,'kab' => 'Ketapang', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '61', 'prov' => 'kalimantanbarat', 'kode_kab' => '6107', 'status' => 'Kabupaten' ,'kab' => 'Sintang', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '61', 'prov' => 'kalimantanbarat', 'kode_kab' => '6108', 'status' => 'Kabupaten' ,'kab' => 'Kapuas Hulu', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '61', 'prov' => 'kalimantanbarat', 'kode_kab' => '6109', 'status' => 'Kabupaten' ,'kab' => 'Sekadau', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '61', 'prov' => 'kalimantanbarat', 'kode_kab' => '6110', 'status' => 'Kabupaten' ,'kab' => 'Melawi', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '61', 'prov' => 'kalimantanbarat', 'kode_kab' => '6111', 'status' => 'Kabupaten' ,'kab' => 'Kayong Utara', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '61', 'prov' => 'kalimantanbarat', 'kode_kab' => '6112', 'status' => 'Kabupaten' ,'kab' => 'Kubu Raya', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '61', 'prov' => 'kalimantanbarat', 'kode_kab' => '6171', 'status' => 'Kota' ,'kab' => 'Pontianak', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '61', 'prov' => 'kalimantanbarat', 'kode_kab' => '6172', 'status' => 'Kota' ,'kab' => 'Singkawang', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '62', 'prov' => 'kalimantantengah', 'kode_kab' => '6201', 'status' => 'Kabupaten' ,'kab' => 'Kotawaringin Barat', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '62', 'prov' => 'kalimantantengah', 'kode_kab' => '6202', 'status' => 'Kabupaten' ,'kab' => 'Kotawaringin Timur', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '62', 'prov' => 'kalimantantengah', 'kode_kab' => '6203', 'status' => 'Kabupaten' ,'kab' => 'Kapuas', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '62', 'prov' => 'kalimantantengah', 'kode_kab' => '6204', 'status' => 'Kabupaten' ,'kab' => 'Barito Selatan', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '62', 'prov' => 'kalimantantengah', 'kode_kab' => '6205', 'status' => 'Kabupaten' ,'kab' => 'Barito Utara', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '62', 'prov' => 'kalimantantengah', 'kode_kab' => '6206', 'status' => 'Kabupaten' ,'kab' => 'Sukamara', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '62', 'prov' => 'kalimantantengah', 'kode_kab' => '6207', 'status' => 'Kabupaten' ,'kab' => 'Lamandau', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '62', 'prov' => 'kalimantantengah', 'kode_kab' => '6208', 'status' => 'Kabupaten' ,'kab' => 'Seruyan', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '62', 'prov' => 'kalimantantengah', 'kode_kab' => '6209', 'status' => 'Kabupaten' ,'kab' => 'Katingan', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '62', 'prov' => 'kalimantantengah', 'kode_kab' => '6210', 'status' => 'Kabupaten' ,'kab' => 'Pulang Pisau', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '62', 'prov' => 'kalimantantengah', 'kode_kab' => '6211', 'status' => 'Kabupaten' ,'kab' => 'Gunung Mas', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '62', 'prov' => 'kalimantantengah', 'kode_kab' => '6212', 'status' => 'Kabupaten' ,'kab' => 'Barito Timur', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '62', 'prov' => 'kalimantantengah', 'kode_kab' => '6213', 'status' => 'Kabupaten' ,'kab' => 'Murung Raya', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '62', 'prov' => 'kalimantantengah', 'kode_kab' => '6271', 'status' => 'Kota' ,'kab' => 'Palangka Raya', 'zona_waktu' => 'WIB'],
            ['kode_prov' => '63', 'prov' => 'kalimantanselatan', 'kode_kab' => '6301', 'status' => 'Kabupaten' ,'kab' => 'Tanah Laut', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '63', 'prov' => 'kalimantanselatan', 'kode_kab' => '6302', 'status' => 'Kabupaten' ,'kab' => 'Kota Baru', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '63', 'prov' => 'kalimantanselatan', 'kode_kab' => '6303', 'status' => 'Kabupaten' ,'kab' => 'Banjar', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '63', 'prov' => 'kalimantanselatan', 'kode_kab' => '6304', 'status' => 'Kabupaten' ,'kab' => 'Barito Kuala', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '63', 'prov' => 'kalimantanselatan', 'kode_kab' => '6305', 'status' => 'Kabupaten' ,'kab' => 'Tapin', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '63', 'prov' => 'kalimantanselatan', 'kode_kab' => '6306', 'status' => 'Kabupaten' ,'kab' => 'Hulu Sungai Selatan', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '63', 'prov' => 'kalimantanselatan', 'kode_kab' => '6307', 'status' => 'Kabupaten' ,'kab' => 'Hulu Sungai Tengah', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '63', 'prov' => 'kalimantanselatan', 'kode_kab' => '6308', 'status' => 'Kabupaten' ,'kab' => 'Hulu Sungai Utara', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '63', 'prov' => 'kalimantanselatan', 'kode_kab' => '6309', 'status' => 'Kabupaten' ,'kab' => 'Tabalong', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '63', 'prov' => 'kalimantanselatan', 'kode_kab' => '6310', 'status' => 'Kabupaten' ,'kab' => 'Tanah Bumbu', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '63', 'prov' => 'kalimantanselatan', 'kode_kab' => '6311', 'status' => 'Kabupaten' ,'kab' => 'Balangan', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '63', 'prov' => 'kalimantanselatan', 'kode_kab' => '6371', 'status' => 'Kota' ,'kab' => 'Banjarmasin', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '63', 'prov' => 'kalimantanselatan', 'kode_kab' => '6372', 'status' => 'Kota' ,'kab' => 'Banjar Baru', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '64', 'prov' => 'kalimantantimur', 'kode_kab' => '6401', 'status' => 'Kabupaten' ,'kab' => 'Paser', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '64', 'prov' => 'kalimantantimur', 'kode_kab' => '6402', 'status' => 'Kabupaten' ,'kab' => 'Kutai Barat', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '64', 'prov' => 'kalimantantimur', 'kode_kab' => '6403', 'status' => 'Kabupaten' ,'kab' => 'Kutai Kartanegara', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '64', 'prov' => 'kalimantantimur', 'kode_kab' => '6404', 'status' => 'Kabupaten' ,'kab' => 'Kutai Timur', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '64', 'prov' => 'kalimantantimur', 'kode_kab' => '6405', 'status' => 'Kabupaten' ,'kab' => 'Berau', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '64', 'prov' => 'kalimantantimur', 'kode_kab' => '6406', 'status' => 'Kabupaten' ,'kab' => 'Malinau', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '64', 'prov' => 'kalimantantimur', 'kode_kab' => '6407', 'status' => 'Kabupaten' ,'kab' => 'Bulungan', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '64', 'prov' => 'kalimantantimur', 'kode_kab' => '6408', 'status' => 'Kabupaten' ,'kab' => 'Nunukan', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '64', 'prov' => 'kalimantantimur', 'kode_kab' => '6409', 'status' => 'Kabupaten' ,'kab' => 'Penajam Paser Utara', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '64', 'prov' => 'kalimantantimur', 'kode_kab' => '6410', 'status' => 'Kabupaten' ,'kab' => 'Tana Tidung', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '64', 'prov' => 'kalimantantimur', 'kode_kab' => '6471', 'status' => 'Kota' ,'kab' => 'Balikpapan', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '64', 'prov' => 'kalimantantimur', 'kode_kab' => '6472', 'status' => 'Kota' ,'kab' => 'Samarinda', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '64', 'prov' => 'kalimantantimur', 'kode_kab' => '6473', 'status' => 'Kota' ,'kab' => 'Tarakan', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '64', 'prov' => 'kalimantantimur', 'kode_kab' => '6474', 'status' => 'Kota' ,'kab' => 'Bontang', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '71', 'prov' => 'sulawesiutara', 'kode_kab' => '7101', 'status' => 'Kabupaten' ,'kab' => 'Bolaang Mongondow', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '71', 'prov' => 'sulawesiutara', 'kode_kab' => '7102', 'status' => 'Kabupaten' ,'kab' => 'Minahasa', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '71', 'prov' => 'sulawesiutara', 'kode_kab' => '7103', 'status' => 'Kabupaten' ,'kab' => 'Kepulauan Sangihe', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '71', 'prov' => 'sulawesiutara', 'kode_kab' => '7104', 'status' => 'Kabupaten' ,'kab' => 'Kepulauan Talaud', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '71', 'prov' => 'sulawesiutara', 'kode_kab' => '7105', 'status' => 'Kabupaten' ,'kab' => 'Minahasa Selatan', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '71', 'prov' => 'sulawesiutara', 'kode_kab' => '7106', 'status' => 'Kabupaten' ,'kab' => 'Minahasa Utara', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '71', 'prov' => 'sulawesiutara', 'kode_kab' => '7107', 'status' => 'Kabupaten' ,'kab' => 'Bolaang Mongondow Utara', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '71', 'prov' => 'sulawesiutara', 'kode_kab' => '7108', 'status' => 'Kabupaten' ,'kab' => 'Siau Tagulandang Biaro', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '71', 'prov' => 'sulawesiutara', 'kode_kab' => '7109', 'status' => 'Kabupaten' ,'kab' => 'Minahasa Tenggara', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '71', 'prov' => 'sulawesiutara', 'kode_kab' => '7110', 'status' => 'Kabupaten' ,'kab' => 'Bolaang Mongondow Selata', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '71', 'prov' => 'sulawesiutara', 'kode_kab' => '7111', 'status' => 'Kabupaten' ,'kab' => 'Bolaang Mongondow Timur', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '71', 'prov' => 'sulawesiutara', 'kode_kab' => '7171', 'status' => 'Kota' ,'kab' => 'Manado', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '71', 'prov' => 'sulawesiutara', 'kode_kab' => '7172', 'status' => 'Kota' ,'kab' => 'Bitung', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '71', 'prov' => 'sulawesiutara', 'kode_kab' => '7173', 'status' => 'Kota' ,'kab' => 'Tomohon', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '71', 'prov' => 'sulawesiutara', 'kode_kab' => '7174', 'status' => 'Kota' ,'kab' => 'Kotamobagu', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '72', 'prov' => 'sulawesitengah', 'kode_kab' => '7201', 'status' => 'Kabupaten' ,'kab' => 'Banggai Kepulauan', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '72', 'prov' => 'sulawesitengah', 'kode_kab' => '7202', 'status' => 'Kabupaten' ,'kab' => 'Banggai', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '72', 'prov' => 'sulawesitengah', 'kode_kab' => '7203', 'status' => 'Kabupaten' ,'kab' => 'Morowali', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '72', 'prov' => 'sulawesitengah', 'kode_kab' => '7204', 'status' => 'Kabupaten' ,'kab' => 'Poso', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '72', 'prov' => 'sulawesitengah', 'kode_kab' => '7205', 'status' => 'Kabupaten' ,'kab' => 'Donggala', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '72', 'prov' => 'sulawesitengah', 'kode_kab' => '7206', 'status' => 'Kabupaten' ,'kab' => 'Toli-toli', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '72', 'prov' => 'sulawesitengah', 'kode_kab' => '7207', 'status' => 'Kabupaten' ,'kab' => 'Buol', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '72', 'prov' => 'sulawesitengah', 'kode_kab' => '7208', 'status' => 'Kabupaten' ,'kab' => 'Parigi Moutong', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '72', 'prov' => 'sulawesitengah', 'kode_kab' => '7209', 'status' => 'Kabupaten' ,'kab' => 'Tojo Una-una', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '72', 'prov' => 'sulawesitengah', 'kode_kab' => '7210', 'status' => 'Kabupaten' ,'kab' => 'Sigi', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '72', 'prov' => 'sulawesitengah', 'kode_kab' => '7271', 'status' => 'Kota' ,'kab' => 'Palu', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '73', 'prov' => 'sulawesiselatan', 'kode_kab' => '7301', 'status' => 'Kabupaten' ,'kab' => 'Kepulauan Selayar', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '73', 'prov' => 'sulawesiselatan', 'kode_kab' => '7302', 'status' => 'Kabupaten' ,'kab' => 'Bulukumba', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '73', 'prov' => 'sulawesiselatan', 'kode_kab' => '7303', 'status' => 'Kabupaten' ,'kab' => 'Bantaeng', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '73', 'prov' => 'sulawesiselatan', 'kode_kab' => '7304', 'status' => 'Kabupaten' ,'kab' => 'Jeneponto', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '73', 'prov' => 'sulawesiselatan', 'kode_kab' => '7305', 'status' => 'Kabupaten' ,'kab' => 'Takalar', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '73', 'prov' => 'sulawesiselatan', 'kode_kab' => '7306', 'status' => 'Kabupaten' ,'kab' => 'Gowa', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '73', 'prov' => 'sulawesiselatan', 'kode_kab' => '7307', 'status' => 'Kabupaten' ,'kab' => 'Sinjai', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '73', 'prov' => 'sulawesiselatan', 'kode_kab' => '7308', 'status' => 'Kabupaten' ,'kab' => 'Maros', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '73', 'prov' => 'sulawesiselatan', 'kode_kab' => '7309', 'status' => 'Kabupaten' ,'kab' => 'Pangkajene Dan Kepulauan', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '73', 'prov' => 'sulawesiselatan', 'kode_kab' => '7310', 'status' => 'Kabupaten' ,'kab' => 'Barru', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '73', 'prov' => 'sulawesiselatan', 'kode_kab' => '7311', 'status' => 'Kabupaten' ,'kab' => 'Bone', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '73', 'prov' => 'sulawesiselatan', 'kode_kab' => '7312', 'status' => 'Kabupaten' ,'kab' => 'Soppeng', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '73', 'prov' => 'sulawesiselatan', 'kode_kab' => '7313', 'status' => 'Kabupaten' ,'kab' => 'Wajo', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '73', 'prov' => 'sulawesiselatan', 'kode_kab' => '7314', 'status' => 'Kabupaten' ,'kab' => 'Sidenreng Rappang', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '73', 'prov' => 'sulawesiselatan', 'kode_kab' => '7315', 'status' => 'Kabupaten' ,'kab' => 'Pinrang', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '73', 'prov' => 'sulawesiselatan', 'kode_kab' => '7316', 'status' => 'Kabupaten' ,'kab' => 'Enrekang', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '73', 'prov' => 'sulawesiselatan', 'kode_kab' => '7317', 'status' => 'Kabupaten' ,'kab' => 'Luwu', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '73', 'prov' => 'sulawesiselatan', 'kode_kab' => '7318', 'status' => 'Kabupaten' ,'kab' => 'Tana Toraja', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '73', 'prov' => 'sulawesiselatan', 'kode_kab' => '7322', 'status' => 'Kabupaten' ,'kab' => 'Luwu Utara', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '73', 'prov' => 'sulawesiselatan', 'kode_kab' => '7325', 'status' => 'Kabupaten' ,'kab' => 'Luwu Timur', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '73', 'prov' => 'sulawesiselatan', 'kode_kab' => '7326', 'status' => 'Kabupaten' ,'kab' => 'Toraja Utara', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '73', 'prov' => 'sulawesiselatan', 'kode_kab' => '7371', 'status' => 'Kota' ,'kab' => 'Makassar', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '73', 'prov' => 'sulawesiselatan', 'kode_kab' => '7372', 'status' => 'Kota' ,'kab' => 'Pare-pare', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '73', 'prov' => 'sulawesiselatan', 'kode_kab' => '7373', 'status' => 'Kota' ,'kab' => 'Palopo', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '74', 'prov' => 'sulawesitenggara', 'kode_kab' => '7401', 'status' => 'Kabupaten' ,'kab' => 'Buton', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '74', 'prov' => 'sulawesitenggara', 'kode_kab' => '7402', 'status' => 'Kabupaten' ,'kab' => 'Muna', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '74', 'prov' => 'sulawesitenggara', 'kode_kab' => '7403', 'status' => 'Kabupaten' ,'kab' => 'Konawe', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '74', 'prov' => 'sulawesitenggara', 'kode_kab' => '7404', 'status' => 'Kabupaten' ,'kab' => 'Kolaka', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '74', 'prov' => 'sulawesitenggara', 'kode_kab' => '7405', 'status' => 'Kabupaten' ,'kab' => 'Konawe Selatan', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '74', 'prov' => 'sulawesitenggara', 'kode_kab' => '7406', 'status' => 'Kabupaten' ,'kab' => 'Bombana', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '74', 'prov' => 'sulawesitenggara', 'kode_kab' => '7407', 'status' => 'Kabupaten' ,'kab' => 'Wakatobi', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '74', 'prov' => 'sulawesitenggara', 'kode_kab' => '7408', 'status' => 'Kabupaten' ,'kab' => 'Kolaka Utara', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '74', 'prov' => 'sulawesitenggara', 'kode_kab' => '7409', 'status' => 'Kabupaten' ,'kab' => 'Buton Utara', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '74', 'prov' => 'sulawesitenggara', 'kode_kab' => '7410', 'status' => 'Kabupaten' ,'kab' => 'Konawe Utara', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '74', 'prov' => 'sulawesitenggara', 'kode_kab' => '7471', 'status' => 'Kota' ,'kab' => 'Kendari', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '74', 'prov' => 'sulawesitenggara', 'kode_kab' => '7472', 'status' => 'Kota' ,'kab' => 'Baubau', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '75', 'prov' => 'gorontalo', 'kode_kab' => '7501', 'status' => 'Kabupaten' ,'kab' => 'Boalemo', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '75', 'prov' => 'gorontalo', 'kode_kab' => '7502', 'status' => 'Kabupaten' ,'kab' => 'Gorontalo', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '75', 'prov' => 'gorontalo', 'kode_kab' => '7503', 'status' => 'Kabupaten' ,'kab' => 'Pohuwato', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '75', 'prov' => 'gorontalo', 'kode_kab' => '7504', 'status' => 'Kabupaten' ,'kab' => 'Bone Bolango', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '75', 'prov' => 'gorontalo', 'kode_kab' => '7505', 'status' => 'Kabupaten' ,'kab' => 'Gorontalo Utara', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '75', 'prov' => 'gorontalo', 'kode_kab' => '7571', 'status' => 'Kota' ,'kab' => 'Gorontalo', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '76', 'prov' => 'sulawesibarat', 'kode_kab' => '7601', 'status' => 'Kabupaten' ,'kab' => 'Majene', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '76', 'prov' => 'sulawesibarat', 'kode_kab' => '7602', 'status' => 'Kabupaten' ,'kab' => 'Polewali Mandar', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '76', 'prov' => 'sulawesibarat', 'kode_kab' => '7603', 'status' => 'Kabupaten' ,'kab' => 'Mamasa', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '76', 'prov' => 'sulawesibarat', 'kode_kab' => '7604', 'status' => 'Kabupaten' ,'kab' => 'Mamuju', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '76', 'prov' => 'sulawesibarat', 'kode_kab' => '7605', 'status' => 'Kabupaten' ,'kab' => 'Mamuju Utara', 'zona_waktu' => 'WITA'],
            ['kode_prov' => '81', 'prov' => 'maluku', 'kode_kab' => '8101', 'status' => 'Kabupaten' ,'kab' => 'Maluku Tenggara Barat', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '81', 'prov' => 'maluku', 'kode_kab' => '8102', 'status' => 'Kabupaten' ,'kab' => 'Maluku Tenggara', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '81', 'prov' => 'maluku', 'kode_kab' => '8103', 'status' => 'Kabupaten' ,'kab' => 'Maluku Tengah', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '81', 'prov' => 'maluku', 'kode_kab' => '8104', 'status' => 'Kabupaten' ,'kab' => 'Buru', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '81', 'prov' => 'maluku', 'kode_kab' => '8105', 'status' => 'Kabupaten' ,'kab' => 'Kepulauan Aru', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '81', 'prov' => 'maluku', 'kode_kab' => '8106', 'status' => 'Kabupaten' ,'kab' => 'Seram Bagian Barat', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '81', 'prov' => 'maluku', 'kode_kab' => '8107', 'status' => 'Kabupaten' ,'kab' => 'Seram Bagian Timur', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '81', 'prov' => 'maluku', 'kode_kab' => '8108', 'status' => 'Kabupaten' ,'kab' => 'Maluku Barat Daya', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '81', 'prov' => 'maluku', 'kode_kab' => '8109', 'status' => 'Kabupaten' ,'kab' => 'Buru Selatan', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '81', 'prov' => 'maluku', 'kode_kab' => '8171', 'status' => 'Kota' ,'kab' => 'Ambon', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '81', 'prov' => 'maluku', 'kode_kab' => '8172', 'status' => 'Kota' ,'kab' => 'Tual', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '82', 'prov' => 'malukuutara', 'kode_kab' => '8201', 'status' => 'Kabupaten' ,'kab' => 'Halmahera Barat', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '82', 'prov' => 'malukuutara', 'kode_kab' => '8202', 'status' => 'Kabupaten' ,'kab' => 'Halmahera Tengah', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '82', 'prov' => 'malukuutara', 'kode_kab' => '8203', 'status' => 'Kabupaten' ,'kab' => 'Kepulauan Sula', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '82', 'prov' => 'malukuutara', 'kode_kab' => '8204', 'status' => 'Kabupaten' ,'kab' => 'Halmahera Selatan', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '82', 'prov' => 'malukuutara', 'kode_kab' => '8205', 'status' => 'Kabupaten' ,'kab' => 'Halmahera Utara', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '82', 'prov' => 'malukuutara', 'kode_kab' => '8206', 'status' => 'Kabupaten' ,'kab' => 'Halmahera Timur', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '82', 'prov' => 'malukuutara', 'kode_kab' => '8207', 'status' => 'Kabupaten' ,'kab' => 'Pulau Morotai', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '82', 'prov' => 'malukuutara', 'kode_kab' => '8271', 'status' => 'Kota' ,'kab' => 'Ternate', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '82', 'prov' => 'malukuutara', 'kode_kab' => '8272', 'status' => 'Kota' ,'kab' => 'Tidore Kepulauan', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '91', 'prov' => 'papuabarat', 'kode_kab' => '9101', 'status' => 'Kabupaten' ,'kab' => 'Fakfak', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '91', 'prov' => 'papuabarat', 'kode_kab' => '9102', 'status' => 'Kabupaten' ,'kab' => 'Kaimana', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '91', 'prov' => 'papuabarat', 'kode_kab' => '9103', 'status' => 'Kabupaten' ,'kab' => 'Teluk Wondama', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '91', 'prov' => 'papuabarat', 'kode_kab' => '9104', 'status' => 'Kabupaten' ,'kab' => 'Teluk Bintuni', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '91', 'prov' => 'papuabarat', 'kode_kab' => '9105', 'status' => 'Kabupaten' ,'kab' => 'Manokwari', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '91', 'prov' => 'papuabarat', 'kode_kab' => '9106', 'status' => 'Kabupaten' ,'kab' => 'Sorong Selatan', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '91', 'prov' => 'papuabarat', 'kode_kab' => '9107', 'status' => 'Kabupaten' ,'kab' => 'Sorong', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '91', 'prov' => 'papuabarat', 'kode_kab' => '9108', 'status' => 'Kabupaten' ,'kab' => 'Raja Ampat', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '91', 'prov' => 'papuabarat', 'kode_kab' => '9109', 'status' => 'Kabupaten' ,'kab' => 'Tambrauw', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '91', 'prov' => 'papuabarat', 'kode_kab' => '9110', 'status' => 'Kabupaten' ,'kab' => 'Maybrat', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '91', 'prov' => 'papuabarat', 'kode_kab' => '9171', 'status' => 'Kota' ,'kab' => 'Sorong', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '94', 'prov' => 'papua', 'kode_kab' => '9401', 'status' => 'Kabupaten' ,'kab' => 'Merauke', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '94', 'prov' => 'papua', 'kode_kab' => '9402', 'status' => 'Kabupaten' ,'kab' => 'Jayawijaya', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '94', 'prov' => 'papua', 'kode_kab' => '9403', 'status' => 'Kabupaten' ,'kab' => 'Jayapura', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '94', 'prov' => 'papua', 'kode_kab' => '9404', 'status' => 'Kabupaten' ,'kab' => 'Nabire', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '94', 'prov' => 'papua', 'kode_kab' => '9408', 'status' => 'Kabupaten' ,'kab' => 'Kepulauan Yapen', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '94', 'prov' => 'papua', 'kode_kab' => '9409', 'status' => 'Kabupaten' ,'kab' => 'Biak Numfor', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '94', 'prov' => 'papua', 'kode_kab' => '9410', 'status' => 'Kabupaten' ,'kab' => 'Paniai', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '94', 'prov' => 'papua', 'kode_kab' => '9411', 'status' => 'Kabupaten' ,'kab' => 'Puncak Jaya', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '94', 'prov' => 'papua', 'kode_kab' => '9412', 'status' => 'Kabupaten' ,'kab' => 'Mimika', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '94', 'prov' => 'papua', 'kode_kab' => '9413', 'status' => 'Kabupaten' ,'kab' => 'Boven Digoel', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '94', 'prov' => 'papua', 'kode_kab' => '9414', 'status' => 'Kabupaten' ,'kab' => 'Mappi', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '94', 'prov' => 'papua', 'kode_kab' => '9415', 'status' => 'Kabupaten' ,'kab' => 'Asmat', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '94', 'prov' => 'papua', 'kode_kab' => '9416', 'status' => 'Kabupaten' ,'kab' => 'Yahukimo', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '94', 'prov' => 'papua', 'kode_kab' => '9417', 'status' => 'Kabupaten' ,'kab' => 'Pegunungan Bintang', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '94', 'prov' => 'papua', 'kode_kab' => '9418', 'status' => 'Kabupaten' ,'kab' => 'Tolikara', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '94', 'prov' => 'papua', 'kode_kab' => '9419', 'status' => 'Kabupaten' ,'kab' => 'Sarmi', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '94', 'prov' => 'papua', 'kode_kab' => '9420', 'status' => 'Kabupaten' ,'kab' => 'Keerom', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '94', 'prov' => 'papua', 'kode_kab' => '9426', 'status' => 'Kabupaten' ,'kab' => 'Waropen', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '94', 'prov' => 'papua', 'kode_kab' => '9427', 'status' => 'Kabupaten' ,'kab' => 'Supiori', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '94', 'prov' => 'papua', 'kode_kab' => '9428', 'status' => 'Kabupaten' ,'kab' => 'Mamberamo Raya', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '94', 'prov' => 'papua', 'kode_kab' => '9429', 'status' => 'Kabupaten' ,'kab' => 'Nduga', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '94', 'prov' => 'papua', 'kode_kab' => '9430', 'status' => 'Kabupaten' ,'kab' => 'Lanny Jaya', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '94', 'prov' => 'papua', 'kode_kab' => '9431', 'status' => 'Kabupaten' ,'kab' => 'Mamberamo Tengah', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '94', 'prov' => 'papua', 'kode_kab' => '9432', 'status' => 'Kabupaten' ,'kab' => 'Yalimo', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '94', 'prov' => 'papua', 'kode_kab' => '9433', 'status' => 'Kabupaten' ,'kab' => 'Puncak', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '94', 'prov' => 'papua', 'kode_kab' => '9434', 'status' => 'Kabupaten' ,'kab' => 'Dogiyai', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '94', 'prov' => 'papua', 'kode_kab' => '9435', 'status' => 'Kabupaten' ,'kab' => 'Intan Jaya', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '94', 'prov' => 'papua', 'kode_kab' => '9436', 'status' => 'Kabupaten' ,'kab' => 'Deiyai', 'zona_waktu' => 'WIT'],
            ['kode_prov' => '94', 'prov' => 'papua', 'kode_kab' => '9436', 'status' => 'Kota' ,'kab' => 'Jayapura', 'zona_waktu' => 'WIT']

        ];

        DB::table('tb_master_kab')->insert($kabkota);
    }

}